name: Release Packer
on:
  push:
    branches:
      - release
jobs:
  pack:
    name: "Pack"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: ${{github.event.commits[0].message}}
          prerelease: false